apiVersion: apps/v1
kind: Deployment
metadata:
  name: furnistyle-deployment
  namespace: furnistyle-frontend
  labels:
    app: furnistyle-frontend-only
spec:
  replicas: 1
  selector:
    matchLabels:
      app: furnistyle-frontend-only
  template:
    metadata:
      labels:
        app: furnistyle-frontend-only
    spec:
      containers:
        - name: furnistyle-front-only
          image: burhan503/furnistyle-frontend
          ports:
            - containerPort: 3000
