apiVersion: v1
kind: Service
metadata:
  name: furnistyle-frontend-service
  namespace: furnistyle-frontend
spec:
  type: ClusterIP
  selector:
    app: furnistyle-frontend-only
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
